class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'Attendance',
      'app_subtitle': 'Modern attendance tracking system',
      'login': 'Login',
      'register': 'Register',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'continue_with_google': 'Continue with Google',
      'continue_with_github': 'Continue with GitHub',
      'continue_with_modder_auth': 'Continue with ModderAuth',
      'register_with_social': 'Register with social accounts',
      'soon': 'SOON',
      'language': 'Language',
      'fill_all_fields': 'Please fill all fields',
      'login_error': 'Login failed. Please try again.',
      'social_login_error': 'Social login failed. Please try again.',
      'coming_soon': 'Coming soon!',
      'reset_password_title': 'Reset Password',
      'reset_password_subtitle': 'Enter your email to receive reset instructions',
      'send_reset_link': 'Send Reset Link',
      'back_to_login': 'Back to Login',
      'enter_email': 'Please enter your email',
      'reset_email_sent': 'Reset email sent successfully',
      'reset_error': 'Failed to send reset email',
      'home': 'Home',
      'attendance': 'Attendance',
      'profile': 'Profile',
      'admin': 'Admin',
      'join_company': 'Join Company',
      'company_username': 'Company Username',
      'search_company': 'Search for company...',
      'send_request': 'Send Request',
      'request_sent': 'Join request sent successfully',
      'company_not_found': 'Company not found',
      'already_requested': 'You have already sent a request to this company',
      'scan_qr': 'Scan QR Code',
      'check_in': 'Check In',
      'check_out': 'Check Out',
      'today_attendance': 'Today\'s Attendance',
      'attendance_history': 'Attendance History',
      'employees': 'Employees',
      'notifications': 'Notifications',
      'settings': 'Settings',
      'add_employee': 'Add Employee',
      'manual_entry': 'Manual Entry',
      'auto_entry': 'Auto Entry',
      'excel_import': 'Excel Import',
      'full_name': 'Full Name',
      'position': 'Position',
      'employee_count': 'Employee Count',
      'generate_employees': 'Generate Employees',
      'import_excel': 'Import Excel File',
      'download_template': 'Download Template',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'approve': 'Approve',
      'reject': 'Reject',
      'pending_requests': 'Pending Requests',
      'no_requests': 'No pending requests',
      'request_approved': 'Request approved successfully',
      'request_rejected': 'Request rejected successfully',
      'employee_added': 'Employee added successfully',
      'employees_generated': 'Employees generated successfully',
      'excel_imported': 'Excel file imported successfully',
      'error_occurred': 'An error occurred',
      'loading': 'Loading...',
      'refresh': 'Refresh',
      'logout': 'Logout',
      'account_switcher': 'Account Switcher',
      'add_account': 'Add Account',
      'switch_account': 'Switch Account',
      'remove_account': 'Remove Account',
      'current_account': 'Current Account',
    },
    'uz': {
      'app_name': 'Davomat',
      'app_subtitle': 'Zamonaviy davomat nazorat tizimi',
      'login': 'Kirish',
      'register': 'Ro\'yxatdan o\'tish',
      'email': 'Email',
      'password': 'Parol',
      'forgot_password': 'Parolni unutdingizmi?',
      'continue_with_google': 'Google orqali davom etish',
      'continue_with_github': 'GitHub orqali davom etish',
      'continue_with_modder_auth': 'ModderAuth orqali davom etish',
      'register_with_social': 'Ijtimoiy tarmoqlar orqali ro\'yxatdan o\'tish',
      'soon': 'TEZDA',
      'language': 'Til',
      'fill_all_fields': 'Barcha maydonlarni to\'ldiring',
      'login_error': 'Kirish muvaffaqiyatsiz. Qaytadan urinib ko\'ring.',
      'social_login_error': 'Ijtimoiy tarmoq orqali kirish muvaffaqiyatsiz.',
      'coming_soon': 'Tezda!',
      'reset_password_title': 'Parolni tiklash',
      'reset_password_subtitle': 'Tiklash yo\'riqnomasini olish uchun emailingizni kiriting',
      'send_reset_link': 'Tiklash havolasini yuborish',
      'back_to_login': 'Kirishga qaytish',
      'enter_email': 'Emailingizni kiriting',
      'reset_email_sent': 'Tiklash emaili muvaffaqiyatli yuborildi',
      'reset_error': 'Tiklash emailini yuborishda xatolik',
      'home': 'Bosh sahifa',
      'attendance': 'Davomat',
      'profile': 'Profil',
      'admin': 'Admin',
      'join_company': 'Kompaniyaga qo\'shilish',
      'company_username': 'Kompaniya username',
      'search_company': 'Kompaniya qidirish...',
      'send_request': 'So\'rov yuborish',
      'request_sent': 'Qo\'shilish so\'rovi muvaffaqiyatli yuborildi',
      'company_not_found': 'Kompaniya topilmadi',
      'already_requested': 'Siz allaqachon bu kompaniyaga so\'rov yuborgansiz',
      'scan_qr': 'QR kod skanerlash',
      'check_in': 'Kelish',
      'check_out': 'Ketish',
      'today_attendance': 'Bugungi davomat',
      'attendance_history': 'Davomat tarixi',
      'employees': 'Xodimlar',
      'notifications': 'Bildirishnomalar',
      'settings': 'Sozlamalar',
      'add_employee': 'Xodim qo\'shish',
      'manual_entry': 'Qo\'lda kiritish',
      'auto_entry': 'Avtomatik kiritish',
      'excel_import': 'Excel import',
      'full_name': 'Ism familiya',
      'position': 'Lavozim',
      'employee_count': 'Xodimlar soni',
      'generate_employees': 'Xodimlar yaratish',
      'import_excel': 'Excel fayl import qilish',
      'download_template': 'Shablon yuklab olish',
      'save': 'Saqlash',
      'cancel': 'Bekor qilish',
      'delete': 'O\'chirish',
      'edit': 'Tahrirlash',
      'approve': 'Tasdiqlash',
      'reject': 'Rad etish',
      'pending_requests': 'Kutilayotgan so\'rovlar',
      'no_requests': 'Kutilayotgan so\'rovlar yo\'q',
      'request_approved': 'So\'rov muvaffaqiyatli tasdiqlandi',
      'request_rejected': 'So\'rov rad etildi',
      'employee_added': 'Xodim muvaffaqiyatli qo\'shildi',
      'employees_generated': 'Xodimlar muvaffaqiyatli yaratildi',
      'excel_imported': 'Excel fayl muvaffaqiyatli import qilindi',
      'error_occurred': 'Xatolik yuz berdi',
      'loading': 'Yuklanmoqda...',
      'refresh': 'Yangilash',
      'logout': 'Chiqish',
      'account_switcher': 'Akkaunt almashtirgich',
      'add_account': 'Akkaunt qo\'shish',
      'switch_account': 'Akkaunt almashtirish',
      'remove_account': 'Akkountni o\'chirish',
      'current_account': 'Joriy akkaunt',
    },
    'ru': {
      'app_name': 'Посещаемость',
      'app_subtitle': 'Современная система учета посещаемости',
      'login': 'Войти',
      'register': 'Регистрация',
      'email': 'Email',
      'password': 'Пароль',
      'forgot_password': 'Забыли пароль?',
      'continue_with_google': 'Продолжить с Google',
      'continue_with_github': 'Продолжить с GitHub',
      'continue_with_modder_auth': 'Продолжить с ModderAuth',
      'register_with_social': 'Регистрация через социальные сети',
      'soon': 'СКОРО',
      'language': 'Язык',
      'fill_all_fields': 'Заполните все поля',
      'login_error': 'Ошибка входа. Попробуйте снова.',
      'social_login_error': 'Ошибка входа через социальную сеть.',
      'coming_soon': 'Скоро!',
      'reset_password_title': 'Сброс пароля',
      'reset_password_subtitle': 'Введите email для получения инструкций',
      'send_reset_link': 'Отправить ссылку сброса',
      'back_to_login': 'Вернуться к входу',
      'enter_email': 'Введите ваш email',
      'reset_email_sent': 'Email для сброса успешно отправлен',
      'reset_error': 'Ошибка отправки email для сброса',
      'home': 'Главная',
      'attendance': 'Посещаемость',
      'profile': 'Профиль',
      'admin': 'Админ',
      'join_company': 'Присоединиться к компании',
      'company_username': 'Username компании',
      'search_company': 'Поиск компании...',
      'send_request': 'Отправить запрос',
      'request_sent': 'Запрос на присоединение успешно отправлен',
      'company_not_found': 'Компания не найдена',
      'already_requested': 'Вы уже отправили запрос в эту компанию',
      'scan_qr': 'Сканировать QR код',
      'check_in': 'Приход',
      'check_out': 'Уход',
      'today_attendance': 'Сегодняшняя посещаемость',
      'attendance_history': 'История посещаемости',
      'employees': 'Сотрудники',
      'notifications': 'Уведомления',
      'settings': 'Настройки',
      'add_employee': 'Добавить сотрудника',
      'manual_entry': 'Ручной ввод',
      'auto_entry': 'Автоматический ввод',
      'excel_import': 'Импорт Excel',
      'full_name': 'Полное имя',
      'position': 'Должность',
      'employee_count': 'Количество сотрудников',
      'generate_employees': 'Создать сотрудников',
      'import_excel': 'Импорт Excel файла',
      'download_template': 'Скачать шаблон',
      'save': 'Сохранить',
      'cancel': 'Отмена',
      'delete': 'Удалить',
      'edit': 'Редактировать',
      'approve': 'Одобрить',
      'reject': 'Отклонить',
      'pending_requests': 'Ожидающие запросы',
      'no_requests': 'Нет ожидающих запросов',
      'request_approved': 'Запрос успешно одобрен',
      'request_rejected': 'Запрос отклонен',
      'employee_added': 'Сотрудник успешно добавлен',
      'employees_generated': 'Сотрудники успешно созданы',
      'excel_imported': 'Excel файл успешно импортирован',
      'error_occurred': 'Произошла ошибка',
      'loading': 'Загрузка...',
      'refresh': 'Обновить',
      'logout': 'Выйти',
      'account_switcher': 'Переключатель аккаунтов',
      'add_account': 'Добавить аккаунт',
      'switch_account': 'Переключить аккаунт',
      'remove_account': 'Удалить аккаунт',
      'current_account': 'Текущий аккаунт',
    },
  };

  static String translate(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ?? 
           _localizedValues['en']?[key] ?? 
           key;
  }
}